### ISSUE TITLE
Crash when entering too long a name for room or mission.

### ISSUE THREAD

**Issue by narhiril** [STL-WomenPlus-Mar22-LiftOff/group-Jessica#17]
Our current room and mission models define a size limit for the database, but don't enforce this limit on form submission, resulting in a crash if the submission is too long.  These models require additional validation attributes.

Steps to reproduce:

1) Go to create a room or mission.
2) Paste in a name that's much too long (I used the Bee Movie copypasta.  I'm not proud).
3) Observe ASP.NET crash report.

**Comment by mmrichmond6** [comment]
Using the same script (which really brought laughter to my 16 year old who said "you know mom that movie is a joke" which I did not but I am learning!) the info is truncated without error by using         [StringLength(50, MinimumLength = 2)].  We can discuss tonight if that is the best fix and whether this fix needs to be applied elsewhere?

**Comment by mmrichmond6** [comment]
Applied the solution described above in branch #40 with pull request sent
